# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=36)),
                ('start_time', models.FloatField()),
                ('completion_time', models.FloatField(default=0.0)),
                ('nrecord', models.IntegerField(default=0)),
                ('currecord', models.IntegerField(default=0)),
                ('status', models.CharField(default=b'JOB_UNKNOWN', max_length=16)),
                ('msg', models.TextField()),
                ('calculation_info', models.TextField()),
                ('pid', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_id', models.IntegerField()),
                ('result_json', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_v2.Job')),
            ],
        ),
    ]
