---
ETOXWS_NAME: etoxwsapi
ETOXWS_APPDIR: "{{APACHE_WEBAPP_DIR}}/{{ETOXWS_NAME}}"

ETOXWS_IMPL_V1:
  PYPATH: ""
  PYPCK: "sampleimpl.ws_impl_v1"
  PYCLASS: "WS1"

ETOXWS_IMPL_V2:
  PYPATH: ""
  PYPCK: "sampleimpl.ws_impl_v2"
  PYCLASS: "WS2"

RDKIT_DIR: "/opt/rdkit"

# if true the database is deleted and re-created
ETOXWS_CLEAN_DB: false

ETOXWS_PRODUCTION: true
# 0: use default by celery which is nr of cores availabe
ETOXWS_NPROC: 0

MQ_NODE: "rabbit@localhost"
MQ_VHOST: "{{ETOXWS_NAME}}"
MQ_USERNAME: "{{ETOXWS_NAME}}"

# The passwords should be overwritten in etoxlabvm.yml when VM should be used
# via internet. For in-house installation in host-only network defaults are okay
ETOXWS_SERVICE_PASSWD: "{{ETOXWS_NAME}}"

