---
- hosts: etoxlab
  vars:
  - APACHE_USE_HTTP: false
#  - ETOXWS_IMPL_V2:
#      PYPATH: "/home/modeler/soft/eTOXlab/ws/"
#      PYPCK: "views2"
#      PYCLASS: "WS2"
  - RDKIT_DIR: "/opt/RDKIT"
  roles:
  - apache
#  - {role: etoxws-server }
  - {role: etoxws-server, ETOXWS_NAME: etoxwsapi_dev }