---
###############################################################################
# Use the PYPATH variable to add your own paths.
# Just add as it was a normal PYTHONPATH,
# PYPATH: "/home/modeler/soft/eTOXlab/ws/:MY_PATH1:MY_PATH2"
###############################################################################
- hosts: etoxlab
  vars:
  - APACHE_USE_HTTP: true
  - ETOXWS_IMPL_V2:
      PYPATH: "/home/modeler/soft/eTOXlab/ws/"
      PYPCK: "views2"
      PYCLASS: "WS2"
  - RDKIT_DIR: "/opt/RDKIT"
  roles:
  - { role: apache }
  - { role: etoxws-server,
      ETOXWS_CLEAN_DB: True,
      ETOXWS_PRODUCTION: True,
#      ETOXWS_SERVICE_PASSWD: secret,
    }
#  - {role: etoxws-server, ETOXWS_NAME: etoxwsapi_dev }
