---
###############################################################################
# Use the PYPATH variable to add your own paths.
# Just add as it was a normal PYTHONPATH,
# PYPATH: "/home/modeler/soft/eTOXlab/ws/:MY_PATH1:MY_PATH2"
###############################################################################
- hosts: etoxlab
  pre_tasks:
  - name: cleanup old and outdated directories
    file: path="{{ item }}" state=absent
    with_items:
    - "/srv/www/webapps/etoxws"
    - "/srv/www/webapps/etoxws-api"
    - "/etc/httpd/conf.d/etox.d"
  - name: set a reasonable prompt
    lineinfile:
      dest: "/home/modeler/.bashrc"
      line: 'export PS1=''\u@\h: \w \$ '''
      regexp: "export PS1="
  roles:
  - { role: apache ,
        tags: apache }
  - { role: apache-vhost ,
        tags: apache }
  - { role: etoxws-server,
        ETOXWS_CLEAN_DB: True,
        when: ETOXWS_PRODUCTION|bool
    }
  - { role: etoxws-server,
        ETOXWS_NAME: etoxwsapi_dev,
        ETOXWS_CLEAN_DB: True,
        when: not ETOXWS_PRODUCTION|bool
    }
       