---
- set_fact:
    SYS_APACHE_SERVICE: httpd
    SYS_APACHE_USER: apache
    SYS_APACHE_GROUP: apache
    SYS_APACHE_PORTS_FILE: "/etc/httpd/conf/httpd.conf"
    SYS_APACHE_CTL: apachectl
    SYS_APACHE_CONF_DIR: "/etc/httpd/conf.d"
    SYS_APACHE_LOG_DIR: "/var/log/httpd"

- name: apache dirs
  file: path="{{item}}" state=directory owner=root group=root
  with_items:
  - "{{VHOST_CONF_DIR}}"
  - "{{VHOST_SSL_DIR}}"

- name: install packages
  yum: name="{{item}}" state=present
  with_items:
  - httpd
  - mod_ssl
  - mod_wsgi
  notify: restart apache

- name: enable required modules
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    line='LoadModule {{item}}_module modules/mod_{{item}}.so'
    insertbefore=BOF
  with_items:
  - ssl
  - wsgi
  notify: restart apache

- name: enable required modules
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    line='WSGISocketPrefix /var/run/wsgi'
    insertbefore=BOF
  notify: restart apache

- name: disable non-standard docroot in brain-dead rhel 
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    regexp='^DocumentRoot'
    state=absent
  notify: restart apache

- file: path={{VHOST_CONF_DIR}} state=directory owner=root group=root

- file: path={{SYS_APACHE_CONF_DIR}}/ssl.conf state=absent
  notify: restart apache

- template: src=ssl.conf dest={{SYS_APACHE_CONF_DIR}}/0-ssl.conf
  notify: restart apache

- template: src=vhost-template.j2 dest={{SYS_APACHE_CONF_DIR}}/{{VHOST_SERVER_NAME}}.conf
  notify: restart apache

