---
# default version is 2.2
- set_fact:
    APACHE_INCLUDE_CONF: Include
    APACHE_VERSION: "2.2"

- name: apache dirs
  file: path="{{item}}" state=directory owner=root group=root
  with_items:
  - "{{APACHE_DOC_ROOT}}"
  - "{{APACHE_WEBAPP_DIR}}"
  - "{{VHOST_DOC_ROOT}}"

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: CentOS.yml
  when: ansible_distribution == "CentOS"

- set_fact: abs_or_pres=absent
- set_fact: abs_or_pres=present
  when: APACHE_USE_HTTP

- lineinfile: dest="{{APACHE_PORTS_FILE}}" regexp='\s*[l|L]isten\s+80' line='Listen 80' state={{abs_or_pres}} insertbefore=BOF
  notify: restart apache

- set_fact: abs_or_pres=absent
- set_fact: abs_or_pres=present
  when: APACHE_USE_HTTPS

- lineinfile: dest="{{APACHE_PORTS_FILE}}" regexp='\s*[l|L]isten\s+443' line='Listen 443' state={{abs_or_pres}} insertbefore=BOF
  notify: restart apache

- include: inc_selfsigned_cert.yml
  when: APACHE_SELFSIGNED_CERT

- name: ensure that we did not mess up apache config
  command: "{{APACHE_CTL}} -t"
  changed_when: false
