---
- set_fact:
    APACHE_PORTS_FILE: "/etc/apache2/ports.conf"
    APACHE_CTL: apache2ctl
    APACHE_SERVICE_NAME: apache2
    APACHE_USER: www-data
    APACHE_GROUP: www-data
    APACHE_CONF_DIR: "/etc/apache2/sites-available"
    APACHE_LOG_DIR: "/var/log/apache2"

# on trusty and later version 2.4 has been introduced
- set_fact:
    APACHE_VERSION: "2.4"
    APACHE_INCLUDE_CONF: IncludeOptional
  when: ansible_lsb.release | version_compare('14.04', '>=')

- name: apache dirs
  file: path="{{item}}" state=directory owner=root group=root
  with_items:
  - "{{VHOST_CONF_DIR}}"
  - "{{VHOST_SSL_DIR}}"

- name: Install Apache2
  apt: name="{{item}}" state=present
  with_items:
  - apache2
  - apache2-utils
  - libapache2-mod-wsgi
  notify: restart apache

- name: Enable apache modules
  apache2_module: state=present name={{item}}
  with_items:
  - ssl
  - wsgi
  notify: restart apache

- name: Enable apache 2.4 modules
  apache2_module: state=present name={{item}}
  with_items:
  - access_compat
  when: ansible_lsb.release | version_compare('14.04', '>=')
  notify: restart apache

- template: src=vhost-template.j2 dest={{APACHE_CONF_DIR}}/{{VHOST_SERVER_NAME}}
  notify: restart apache

- shell: a2ensite {{VHOST_SERVER_NAME}}
  register: r
  changed_when: not "already" in r.stdout
  notify: restart apache

- shell: a2dissite {{item}}
  changed_when: false
  ignore_errors: yes
  with_items:
  - default
  - default-ssl
  
  notify: restart apache

