---
- set_fact:
    APACHE_PORTS_FILE: "/etc/apache2/ports.conf"
    APACHE_CTL: apache2ctl
    APACHE_SERVICE_NAME: apache2
    APACHE_USER: www-data
    APACHE_GROUP: www-data
    APACHE_CONF_DIR: "/etc/apache2/sites-available"
    APACHE_LOG_DIR: "/var/log/apache2"

- name: Install Apache2
  apt: name="{{item}}" state=present
  with_items:
  - apache2
  - apache2-utils
  - libapache2-mod-wsgi
  notify: restart apache

