---
- set_fact:
    SYS_APACHE_SERVICE: apache2
    SYS_APACHE_USER: www-data
    SYS_APACHE_GROUP: www-data
    SYS_APACHE_PORTS_FILE: "/etc/apache2/ports.conf"
    SYS_APACHE_CTL: apache2ctl
    SYS_APACHE_CONF_DIR: "/etc/apache2/sites-available"
    SYS_APACHE_LOG_DIR: "/var/log/apache2"
- set_fact:
    _vhost_conf: "{{SYS_APACHE_CONF_DIR}}/{{VHOST_SERVER_NAME}}"

# on trusty and later version 2.4 has been introduced
- set_fact:
    SYS_APACHE_VERSION: "2.4"
    SYS_APACHE_INCLUDE_CONF: IncludeOptional
  when: ansible_lsb.release | version_compare('14.04', '>=')
- set_fact:
    _vhost_conf: "{{SYS_APACHE_CONF_DIR}}/{{VHOST_SERVER_NAME}}.conf"
  when: ansible_lsb.release | version_compare('14.04', '>=')

- name: apache dirs
  file: path="{{item}}" state=directory owner=root group=root
  with_items:
  - "{{VHOST_CONF_DIR}}"
  - "{{VHOST_SSL_DIR}}"

- name: Install Apache2
  apt: name="{{item}}" state=present update_cache=yes
  with_items:
  - apache2
  - apache2-utils
  - libapache2-mod-wsgi
  notify: restart apache

- name: Enable apache modules
  apache2_module: state=present name={{item}}
  with_items:
  - ssl
  - wsgi
  notify: restart apache

- name: Enable apache 2.4 modules
  apache2_module: state=present name={{item}}
  with_items:
  - access_compat
  when: ansible_lsb.release | version_compare('14.04', '>=')
  notify: restart apache

- template: src=vhost-template.j2 dest={{_vhost_conf}}
  notify: restart apache

- shell: a2ensite {{VHOST_SERVER_NAME}}
  register: r
  changed_when: not "already" in r.stdout
  notify: restart apache

- shell: a2dissite {{item}}
  changed_when: false
  ignore_errors: yes
  with_items:
  - default
  - default-ssl
  - 000-default
  - 000-default-ssl
  
  notify: restart apache

