---

#- name: install required packages
#  yum: name="{{item}}" state=present
#  with_items:
##  - postgresql92
##  - python-psycopg2
#  - sudo
#  - byobu
  
- name: create link for rabbitmq-plugins in /usr/local/bin
  file: src=/usr/lib/rabbitmq/bin/{{item}} dest=/usr/local/bin/{{item}} state=link
  with_items:
  - rabbitmq-defaults
  - rabbitmq-env
  - rabbitmq-plugins

- include: install_pip_supervisord.yml
