---
# why the hack they have the version number in the package name? or provide a meta-package ...
- include: "CentOS-6.yml"
  when: ansible_distribution_major_version == "6"
  
- include: "CentOS-7.yml"
  when: ansible_distribution_major_version == "7"

- name: cleanup old files from previous versions
  file: path=/etc/httpd/conf.d/{{item}} state=absent
  with_items:
  - wsgi.conf
  - XXXetox
  - z_etoxws-api-v2.conf
  - z_etoxws.conf
  