---
- name: install EPEL repo
  yum: name=epel-release

- name: install required packages
  yum: name="{{item}}" state=present
  with_items:
  - "@Development Tools"
  - postgresql-devel
  - rabbitmq-server
  - librabbitmq-devel
  - librabbitmq
  - libyaml-devel
  - postgresql-server
  - python-psycopg2
  - python-virtualenv
  - supervisor
  - git
  - sudo
  - byobu

- name: init postgres
  shell: postgresql-setup initdb
  args:
    creates: "{{postgres_main_conf}}"

- service: name={{ item }} state=started enabled=yes
  with_items:
  - supervisord
  - postgresql

#- name: create link for rabbitmq-plugins in /usr/local/bin
#  file: src=/usr/lib/rabbitmq/bin/{{item}} dest=/usr/local/bin/{{item}} state=link
#  with_items:
#  - rabbitmq-defaults
#  - rabbitmq-env
#  - rabbitmq-plugins
#  when: ansible_distribution_major_version == "6"
  