---
- name: install required packages
  apt: name="{{item}}" state=present update_cache=yes
  with_items:
  - supervisor
  - rabbitmq-server
  - libyaml-dev
  - postgresql
  - python-psycopg2
  - build-essential
  - git
  - python-virtualenv
  - python-dev
  - libpq-dev
  - sudo

- name: Enable apache modules
  apache2_module: state=present name={{item}}
  with_items:
  - headers
  